sonar.projectKey=ShlomoChanoch_cicd-oci

sonar.organization=shlomochanoch

sonar.projectName=cicd-oci

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py

sonar.python.coverage.reportPaths=coverage.xml